name: "Lesson 4 - Exercise 3"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-guidelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add guidelines
        run: |
          gh auth login --with-token <<<"${{ secrets.GITHUB_TOKEN }}"

          gh issue \
            comment ${{ github.event.issue.number }} \
            --body-file ./guidelines.md
